export const BRANDS = [
  "Honda",
  "Suzuki",
  "Yamaha",
  "Kawasaki",
  "United",
  "Harley-Davidson",
  "Royal Enfield",
  "KTM",
  "Bajaj",
  "Hero",
  "Jawa",
  "CFMoto",
  "Ducati",
  "Triumph",
  "TVS",
  "Qingqi",
  "Jiajiale",
  "Vespa",
  "Volkswagen",
  "Peugeot",
  "Road Prince",
];

export const BRAND_MODELS = {
  Honda: [
    "CD 70",
    "CG 125",
    "CG 150",
    "CB 150",
    "CB 125",
    "CB 300",
    "CBR 150R",
    "CBR 250R",
    "CBR 600RR",
    "PCX 150",
    "Shine 125",
    "Hornet 2.0",
    "XRE 300",
    "CB 500F",
    "Africa Twin",
    "NC 750X",
    "Gold Wing",
    "Rebel 500",
  ],
  Suzuki: [
    "GSX-R 150",
    "Gixxer 155",
    "Gixxer SF 155",
    "Hayabusa",
    "V-Strom 650",
    "Burgman Street 125",
    "Access 125",
    "Intruder 150",
    "Gixxer 250",
    "V-Strom 1050",
    "GSX-S1000",
    "Katana",
  ],
  Yamaha: [
    "YBR 125",
    "FZ-S",
    "Fazer 25",
    "MT-15",
    "R15 V4",
    "Vixion R",
    "Aerox 155",
    "Fascino 125",
    "MT-07",
    "MT-09",
    "R6",
    "YZF-R1",
    "NMAX",
    "XMAX",
    "Tenere 700",
    "Tracer 9",
  ],
  Kawasaki: [
    "Ninja 300",
    "Ninja 400",
    "Z650",
    "Z900",
    "Vulcan S",
    "Versys 650",
    "Versys 1000",
    "Z1000",
    "Ninja ZX-10R",
    "Ninja ZX-14R",
    "KX 450",
    "KLR 650",
  ],
  United: [
    "US 70",
    "US 100",
    "US 125",
  ],
  "Harley-Davidson": [
    "Street 500",
    "Street 750",
    "Panhead",
    "Fat Boy",
    "Softail Standard",
    "Heritage Classic",
    "Road King",
    "Street Glide",
    "Road Glide",
    "CVO Limited",
    "Iron 883",
    "Forty-Eight",
  ],
  "Royal Enfield": [
    "Classic 350",
    "Classic 650",
    "Meteor 350",
    "Himalayan",
    "Himalayan 452",
    "Continental GT 650",
    "Interceptor 650",
    "Bullet 350",
    "Hunter 350",
    "Scram 440",
    "Shotgun 650",
  ],
  KTM: [
    "Duke 200",
    "Duke 390",
    "Duke 790",
    "Duke 890",
    "Duke 1290",
    "RC 390",
    "RC 8C",
    "1290 Super Duke R",
    "1290 Super Duke GT",
    "790 Adventure",
    "890 Adventure",
    "1290 Super Adventure R",
    "350 SX-F",
    "450 SX-F",
    "690 Enduro R",
  ],
  Bajaj: [
    "Pulsar 150",
    "Pulsar 220F",
    "Pulsar N250",
    "Pulsar NS200",
    "Pulsar NS400Z",
    "Avenger 220",
    "Avenger 400",
    "Avenger Street 220",
    "Dominar 400",
    "Dominar 600",
    "CT 100",
    "CT 125X",
    "Pulsar 160",
    "Pulsar N160",
  ],
  Hero: [
    "Splendor Plus",
    "Splendor iSmart",
    "HF Deluxe",
    "Passion Pro",
    "Passion Xpulse",
    "Xtreme 160R",
    "Xtreme 200S",
    "Xtreme 2004i",
    "Glamour",
    "Glamour Hunk",
    "Xpulse 200",
    "Mavrick 440",
    "Karizma XMR",
    "Xtreme 160 4V",
  ],
  Jawa: [
    "Jawa 42",
    "Jawa Classic",
    "Perak 293",
    "Jawa 42 Coil",
    "Jawa Classic Stealth",
  ],
  CFMoto: ["NK 250", "NK 400", "NK 650", "ZForce 800", "MT 800", "UForce 800"],
  Ducati: [
    "Monster",
    "Scrambler",
    "Scrambler Icon",
    "Scrambler Desert Sled",
    "Panigale V2",
    "Panigale V4",
    "Panigale V4 S",
    "Multistrada",
    "Multistrada V2",
    "Multistrada V4",
    "Diavel",
    "Diavel V4",
    "Streetfighter V2",
    "Streetfighter V4",
    "DesertX",
    "Hypermotard",
  ],
  Triumph: [
    "Street Twin",
    "Street Scrambler",
    "Tiger 900",
    "Tiger 1200",
    "Bonneville T100",
    "Bonneville T120",
    "Bonneville Speed Twin",
    "Thruxton",
    "Rocket 3",
    "Tiger 1200 GT",
    "Scrambler 1200",
  ],
  TVS: [
    "Apache RTR 160 4V",
    "Apache RTR 200 4V",
    "Apache RTR 310",
    "Jupiter",
    "Ntorq 125",
    "Ntorq 150",
    "Ronin",
    "Raider 125",
    "Sportz",
    "Sportz 125",
    "TVS NX 300",
  ],
  Qingqi: ["QS 150", "QS 125", "QS 200"],
  Jiajiale: ["JJ150", "JJ125"],
  Vespa: ["Vespa Primavera", "Vespa Sprint", "Vespa GTS", "Vespa LX 125", "Vespa 150"],
  Volkswagen: ["Evo 200", "Evo 150"],
  Peugeot: ["Vivacity", "Streetzone", "Speedfight", "Landrix"],
  "Road Prince": [
    "RP 70",
    "RP 110",
    "RP 125",
    "RP 125 Euro II",
    "RP 70cc",
    "RP 125cc",
    "Wego 125",
    "RP 100",
  ],
};

export const YEARS = Array.from({ length: 38 }, (_, i) => 1990 + i);

export const COLORS = [
  "Black",
  "White",
  "Red",
  "Blue",
  "Green",
  "Silver",
  "Grey",
  "Orange",
  "Yellow",
  "Beige",
  "Brown",
  "Maroon",
  "Purple",
  "Pink",
  "Matte Black",
  "Pearl White",
  "Dark Grey",
  "Light Blue",
  "Military Green",
];

export const ENGINES = [
  50, 70, 100, 110, 125, 150, 160, 180, 200, 220, 250, 300, 350, 375,
  400, 450, 500, 600, 650, 750, 790, 800, 900, 1000,
];

export const CITIES = [
  "Lahore",
  "Karachi",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Hyderabad",
  "Quetta",
  "Peshawar",
  "Sialkot",
  "Gujranwala",
  "Bahawalpur",
  "Sukkur",
  "Larkana",
  "Mardan",
  "Abbottabad",
  "Sargodha",
  "Dera Ismail Khan",
  "Rahim Yar Khan",
  "Gwadar",
  "Sahiwal",
  "Okara",
  "Kasur",
  "Sheikhupura",
  "Sialkot",
  "Gujrat",
  "Jhang",
  "Dera Ghazi Khan",
  "Zhob",
  "Turbat",
  "Kech",
  "Jacobabad",
  "Bannu",
  "Lakki Marwat",
  "Tank",
  "Hangu",
  "Kohat",
  "Charsadda",
  "Swabi",
  "Nowshera",
  "Chitral",
  "Dir",
  "Swat",
  "Mansehra",
  "Abbottabad",
  "Haripur",
  "Karak",
  "Havelian",
];

export const PROVINCES = [
  "Punjab",
  "Sindh",
  "Khyber Pakhtunkhwa",
  "Balochistan",
  "Gilgit-Baltistan",
  "Azad Kashmir",
  "Islamabad Capital Territory",
];

export function getModels(brand) {
  return BRAND_MODELS[brand] || [];
}
